apiVersion: v1
kind: Service
metadata:
  name: vault
spec:
  ports:
  - port: 8200
    protocol: TCP
    targetPort: 8200
  selector:
    app: vault
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: vault
  name: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  strategy: {}
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - image: vault
        name: vault
        command: ["/bin/vault", "server", "-config=/run/vault-config/vault.hcl"]
        ports:
        - containerPort: 8200
        env:
        - name: ETCD_HA_ENABLED
          value: "false"
        resources: {}
        volumeMounts:
        - name: vault-config-volume
          mountPath: /run/vault-config
        - name: vault-server-tls
          mountPath: /run/vault-listener/
        - name: vault-etcd-client-tls
          mountPath: /run/vault-etcd/
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
      volumes:
        - name: vault-config-volume
          configMap:
            name: vault
        - name: vault-server-tls
          secret:
            defaultMode: 420
            secretName: vault-server-tls
        - name: vault-etcd-client-tls
          secret:
            defaultMode: 420
            secretName: vault-etcd-client-tls

status: {}
